/*
 * Behavioral Bridge — canonical consultation bridge v2
 *
 * LIVE WIX STATE (authoritative as of 2026-09-03):
 *   Canonical custom embed ID: b3ececaf-c221-4ad1-9590-4aa112486e11
 *   Canonical live revision: 9
 *   Duplicate/legacy connector ID: 0ac3fcaf-b699-42da-9867-972e09d58b75 (DISABLED, rev 5)
 *   Target route: /consultation
 *   Wix Form ID: b692e647-b20c-45b0-ae1d-2530df030907
 *   Vibe OAuth client ID: 1e6ddb20-006b-4ce7-ab4b-fd4316f6f161 (public client ID; not a secret)
 *   Fallback email: Ryan_Carvalho@BehavioralBridge.org
 *
 * REVISION NOTE:
 *   Revision 8 added a 60-second sessionStorage same-request dedupe guard after
 *   a successful test. The next two user tests were not recorded in Wix, so
 *   that guard was reverted at live revision 9. The existing in-flight `busy`
 *   flag remains as the duplicate-click protection because the pre-guard
 *   implementation is the last known working path.
 *
 * MERGED FROM BOTH WORKSTREAMS:
 *   - preserves/intercepts the existing Vibe consultation form when present
 *   - renders a controlled fallback form only when the native form is unavailable
 *   - uses Bearer visitor authentication
 *   - requests CONFIRMED Wix submission status and verifies the returned status
 *   - never shows a false success for PENDING/unconfirmed submissions
 *   - normalizes phone values before Wix Forms submission
 *   - opens a prefilled email fallback if Wix cannot confirm the submission
 *   - keeps only one live handler to prevent competing listeners/race conditions
 *
 * IMPORTANT: GPT-Work is version control/recovery documentation, not yet the
 * Wix-generated Vibe source checkout. Editing this file does not itself deploy
 * to Wix. The live copy is managed by the canonical Custom Embed above.
 */
(function(){
if(window.__BB_CONSULT_CANONICAL_V2__)return;window.__BB_CONSULT_CANONICAL_V2__=true;
var CLIENT='1e6ddb20-006b-4ce7-ab4b-fd4316f6f161',FORM='b692e647-b20c-45b0-ae1d-2530df030907',EMAIL='Ryan_Carvalho@BehavioralBridge.org',FALLBACK='bb-consult-fallback',busy=false;
function onPage(){return /\/consultation\/?$/i.test(location.pathname||'')||/consult/i.test(location.hash||'')}
function controls(root){return Array.prototype.slice.call((root||document).querySelectorAll('input,textarea,select')).filter(function(el){return !['hidden','submit','button'].includes(el.type)})}
function formLike(el){var f=el&&el.closest&&el.closest('form');if(f)return f;var n=el;for(var i=0;n&&i<8;i++,n=n.parentElement){if(controls(n).length>=3)return n}return null}
function desc(el){var a=[el.name,el.id,el.placeholder,el.getAttribute('aria-label'),el.getAttribute('autocomplete')];if(el.id){document.querySelectorAll('label[for="'+CSS.escape(el.id)+'"]').forEach(function(l){a.push(l.textContent)})}var w=el.closest&&el.closest('label');if(w)a.push(w.textContent);var p=el.parentElement;if(p)Array.prototype.slice.call(p.children).filter(function(x){return x!==el&&!x.querySelector('input,textarea,select')}).slice(0,3).forEach(function(x){a.push(x.textContent)});return a.filter(Boolean).join(' ').replace(/\s+/g,' ').trim().toLowerCase()}
function val(el){if(el.type==='checkbox')return el.checked?(el.value||'Yes'):'';if(el.type==='radio')return el.checked?el.value:'';return (el.value||'').trim()}
function pick(items,tests){for(var i=0;i<tests.length;i++){var hit=items.find(function(x){return val(x.el)&&tests[i](x.d)});if(hit)return val(hit.el)}return ''}
function splitName(x){var p=(x||'').trim().split(/\s+/).filter(Boolean);if(!p.length)return['',''];if(p.length===1)return[p[0],'Visitor'];return[p.slice(0,-1).join(' '),p[p.length-1]]}
function phone(x){var v=(x||'').trim(),d=v.replace(/\D/g,'');if(!v)return'';if(d.length===10)return'+1'+d;if(d.length===11&&d[0]==='1')return'+'+d;if(v[0]==='+'&&d.length>=10)return'+'+d;return''}
function collect(root){var items=controls(root).map(function(el){return{el:el,d:desc(el)}}),first=pick(items,[function(d){return/first.*name|name.*first/.test(d)&&!/student/.test(d)}]),last=pick(items,[function(d){return/last.*name|name.*last/.test(d)&&!/student/.test(d)}]),full=pick(items,[function(d){return/(parent|contact|your).*name|name.*(parent|contact)/.test(d)&&!/first|last|student/.test(d)},function(d){return/^name$/.test(d.trim())}]);if((!first||!last)&&full){var s=splitName(full);first=first||s[0];last=last||s[1]}return{first_name_bb:first||'Website',last_name_bb:last||'Visitor',email_bb:pick(items,[function(d){return/email/.test(d)}]),phone_bb:phone(pick(items,[function(d){return/phone|mobile|telephone/.test(d)}])),student_name_bb:pick(items,[function(d){return/student.*name|name.*student/.test(d)}])||'Not provided',student_grade_bb:pick(items,[function(d){return/grade|year in school|student year/.test(d)}])||'Not provided',goals_bb:pick(items,[function(d){return/goal|challenge|help with|looking for|message|tell us|tell me|primary need|how can/.test(d)}])||'Consultation request submitted through the Behavioral Bridge website.',availability_bb:pick(items,[function(d){return/availability|preferred.*time|preferred.*day|schedule/.test(d)}])}}
function status(root,text,ok){var box=root.querySelector&&root.querySelector('[data-bb-consult-status]');if(!box){box=document.createElement('div');box.setAttribute('data-bb-consult-status','1');box.setAttribute('role','status');box.style.marginTop='12px';box.style.fontSize='14px';box.style.lineHeight='1.45';var btn=root.querySelector('button[type="submit"],input[type="submit"],button');(btn&&btn.parentNode?btn.parentNode:root).appendChild(box)}box.textContent=text;box.style.color=ok?'inherit':'#8b1e1e'}
async function token(){var r=await fetch('https://www.wixapis.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:CLIENT,grantType:'anonymous'})});if(!r.ok)throw Error('AUTH-'+r.status);var j=await r.json();if(!j.access_token)throw Error('NO_TOKEN');return j.access_token}
async function submit(data,t,confirmed){var sub={formId:FORM,submissions:data};if(confirmed)sub.status='CONFIRMED';return fetch('https://www.wixapis.com/forms/v4/submissions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify({submission:sub})})}
function emailFallback(root,data){var subject='Behavioral Bridge Consultation Request',body=['New Behavioral Bridge consultation request','','Parent / Contact: '+[data.first_name_bb,data.last_name_bb].filter(Boolean).join(' '),'Email: '+(data.email_bb||''),'Phone: '+(data.phone_bb||''),'Student: '+(data.student_name_bb||''),'Grade: '+(data.student_grade_bb||''),'','Goals / Help Requested:',data.goals_bb||'','','General Availability:',data.availability_bb||''].join('\n');status(root,'Your email app is opening with your consultation request prepared. Please press Send there to complete your request.',true);location.href='mailto:'+EMAIL+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body)}
function clear(root){root.querySelectorAll('input,textarea').forEach(function(el){if(!['submit','button','hidden'].includes(el.type))el.value=''});root.querySelectorAll('select').forEach(function(el){el.selectedIndex=0})}
async function send(root,btn){if(busy)return;var data=collect(root);if(!data.email_bb||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email_bb)){status(root,'Please enter a valid email address before submitting.',false);return}busy=true;if(btn)btn.disabled=true;status(root,'Sending your consultation request…',true);try{var t=await token(),r=await submit(data,t,true);if(!r.ok&&(r.status===400||r.status===403))r=await submit(data,t,false);var txt=await r.text(),j={};try{j=txt?JSON.parse(txt):{}}catch(_){}if(!r.ok)throw Error('SUBMIT-'+r.status);if(!j.submission||j.submission.status!=='CONFIRMED'){console.info('[Behavioral Bridge] Wix submission not confirmed; using email fallback');emailFallback(root,data);return}status(root,'Thank you. Your consultation request has been received. Ryan will follow up by email.',true);clear(root)}catch(e){console.error('[Behavioral Bridge consultation]',e&&e.message?e.message:e);emailFallback(root,data)}finally{busy=false;if(btn)btn.disabled=false}}
function eligible(btn,root){if(!btn||!root||controls(root).length<3)return false;var t=(btn.textContent||btn.value||'').toLowerCase();return btn.type==='submit'||/request.*consult|book.*consult|submit|send|start.*consult/.test(t)}
function nativeRoot(){var fs=Array.prototype.slice.call(document.querySelectorAll('form')).filter(function(f){return !f.closest('#'+FALLBACK)&&controls(f).length>=3});var scored=fs.map(function(f){var d=controls(f).map(desc).join(' '),score=(/email/.test(d)?3:0)+(/student|grade/.test(d)?2:0)+(/goal|help|message|challenge/.test(d)?2:0);return{f:f,score:score}}).sort(function(a,b){return b.score-a.score});return scored.length&&scored[0].score>=3?scored[0].f:null}
function renderFallback(){if(!onPage()||nativeRoot()||document.getElementById(FALLBACK))return;var x=document.createElement('section');x.id=FALLBACK;x.style.cssText='box-sizing:border-box;width:min(1040px,calc(100% - 32px));margin:30px auto 46px;padding:32px;background:#15171a;color:#f5f5f5;border:1px solid #34383e;border-radius:22px;font-family:Arial,Helvetica,sans-serif';x.innerHTML='<h2 style="margin:0 0 10px;font-size:34px">Request a Consultation</h2><p style="color:#cfd2d6;line-height:1.5">Tell me a little about the student and what you want to improve. I’ll follow up by email with the best next step.</p><form id="bbcf"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><input name="firstName" placeholder="Parent / Contact First Name" required><input name="lastName" placeholder="Parent / Contact Last Name" required><input name="email" type="email" placeholder="Email" required><input name="phone" type="tel" placeholder="Phone"><input name="studentName" placeholder="Student Name" required><input name="studentGrade" placeholder="Student Grade" required><textarea name="goals" placeholder="What are you looking for help with?" required style="grid-column:1/-1;min-height:100px"></textarea><textarea name="availability" placeholder="General Availability" style="grid-column:1/-1;min-height:80px"></textarea><button type="submit" style="grid-column:1/-1;padding:13px;border-radius:999px;border:0;font-weight:700">Request Consultation</button></div></form>';x.querySelectorAll('input,textarea').forEach(function(el){el.style.cssText+=';box-sizing:border-box;width:100%;padding:12px;border-radius:10px;border:1px solid #484d54;background:#0d0e10;color:#fff'});var host=document.querySelector('main')||document.querySelector('[role=main]')||document.body;host.appendChild(x);var f=x.querySelector('form');f.addEventListener('submit',function(e){e.preventDefault();e.stopPropagation();send(f,f.querySelector('button'))})}
function sync(){if(!onPage()){var old=document.getElementById(FALLBACK);if(old)old.remove();return}var n=nativeRoot(),old=document.getElementById(FALLBACK);if(n&&old)old.remove();if(!n)renderFallback()}
document.addEventListener('submit',function(e){if(!onPage()||e.target.closest&&e.target.closest('#'+FALLBACK))return;var root=formLike(e.target);if(!root||controls(root).length<3)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();send(root,root.querySelector('button[type="submit"],input[type="submit"]'))},true);
document.addEventListener('click',function(e){if(!onPage()||e.target.closest&&e.target.closest('#'+FALLBACK))return;var btn=e.target&&e.target.closest&&e.target.closest('button,input[type="submit"]'),root=formLike(btn);if(!eligible(btn,root))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();send(root,btn)},true);
sync();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});[600,1600,3200].forEach(function(ms){setTimeout(sync,ms)});addEventListener('popstate',function(){setTimeout(sync,0)});console.info('[Behavioral Bridge] canonical consultation bridge v2 active');
})();
